# Generated by Django 5.0.2 on 2025-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
